// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx_token_pay.proto

//包名，通过protoc生成时go文件时

package go_protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxTokenPay struct {
	TxBase               *TxBase  `protobuf:"bytes,1,opt,name=TxBase,proto3" json:"TxBase,omitempty"`
	Token_VinTotal       uint64   `protobuf:"varint,2,opt,name=Token_Vin_total,json=TokenVinTotal,proto3" json:"Token_Vin_total,omitempty"`
	Token_Vin            []*Vin   `protobuf:"bytes,3,rep,name=Token_Vin,json=TokenVin,proto3" json:"Token_Vin,omitempty"`
	Token_VoutTotal      uint64   `protobuf:"varint,4,opt,name=Token_Vout_total,json=TokenVoutTotal,proto3" json:"Token_Vout_total,omitempty"`
	Token_Vout           []*Vout  `protobuf:"bytes,5,rep,name=Token_Vout,json=TokenVout,proto3" json:"Token_Vout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxTokenPay) Reset()         { *m = TxTokenPay{} }
func (m *TxTokenPay) String() string { return proto.CompactTextString(m) }
func (*TxTokenPay) ProtoMessage()    {}
func (*TxTokenPay) Descriptor() ([]byte, []int) {
	return fileDescriptor_802412a3d36ae489, []int{0}
}
func (m *TxTokenPay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxTokenPay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxTokenPay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxTokenPay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxTokenPay.Merge(m, src)
}
func (m *TxTokenPay) XXX_Size() int {
	return m.Size()
}
func (m *TxTokenPay) XXX_DiscardUnknown() {
	xxx_messageInfo_TxTokenPay.DiscardUnknown(m)
}

var xxx_messageInfo_TxTokenPay proto.InternalMessageInfo

func (m *TxTokenPay) GetTxBase() *TxBase {
	if m != nil {
		return m.TxBase
	}
	return nil
}

func (m *TxTokenPay) GetToken_VinTotal() uint64 {
	if m != nil {
		return m.Token_VinTotal
	}
	return 0
}

func (m *TxTokenPay) GetToken_Vin() []*Vin {
	if m != nil {
		return m.Token_Vin
	}
	return nil
}

func (m *TxTokenPay) GetToken_VoutTotal() uint64 {
	if m != nil {
		return m.Token_VoutTotal
	}
	return 0
}

func (m *TxTokenPay) GetToken_Vout() []*Vout {
	if m != nil {
		return m.Token_Vout
	}
	return nil
}

func init() {
	proto.RegisterType((*TxTokenPay)(nil), "go_protos.TxTokenPay")
}

func init() { proto.RegisterFile("tx_token_pay.proto", fileDescriptor_802412a3d36ae489) }

var fileDescriptor_802412a3d36ae489 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xa9, 0x88, 0x2f,
	0xc9, 0xcf, 0x4e, 0xcd, 0x8b, 0x2f, 0x48, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x4c, 0xcf, 0x8f, 0x07, 0xb3, 0x8a, 0xa5, 0x78, 0x4a, 0x2a, 0x92, 0x12, 0x8b, 0x53, 0x21, 0x12,
	0x4a, 0xcf, 0x18, 0xb9, 0xb8, 0x42, 0x2a, 0x42, 0x40, 0xca, 0x03, 0x12, 0x2b, 0x85, 0x34, 0xb9,
	0xd8, 0x42, 0x2a, 0x9c, 0x12, 0x8b, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x04, 0xf5,
	0xe0, 0x1a, 0xf5, 0x20, 0x12, 0x41, 0x50, 0x05, 0x42, 0x6a, 0x5c, 0xfc, 0x60, 0x6d, 0xf1, 0x61,
	0x99, 0x79, 0xf1, 0x25, 0xf9, 0x25, 0x89, 0x39, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0xbc,
	0x60, 0xe1, 0xb0, 0xcc, 0xbc, 0x10, 0x90, 0xa0, 0x90, 0x36, 0x17, 0x27, 0x5c, 0x9d, 0x04, 0xb3,
	0x02, 0xb3, 0x06, 0xb7, 0x11, 0x1f, 0x92, 0xa9, 0x61, 0x99, 0x79, 0x41, 0x1c, 0x30, 0x1d, 0x42,
	0x1a, 0x5c, 0x02, 0x50, 0xc5, 0xf9, 0xa5, 0x25, 0x50, 0x53, 0x59, 0xc0, 0xa6, 0xf2, 0x41, 0xd4,
	0xe4, 0x97, 0x96, 0x40, 0x8c, 0xd5, 0xe3, 0xe2, 0x42, 0xa8, 0x94, 0x60, 0x05, 0x9b, 0xcb, 0x8f,
	0x6c, 0x6e, 0x7e, 0x69, 0x49, 0x10, 0x27, 0x5c, 0x93, 0x93, 0xec, 0x89, 0x47, 0x72, 0x8c, 0x17,
	0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe3, 0xb1, 0x1c, 0x43, 0x14, 0xb7, 0x9e, 0x3e,
	0x5c, 0x79, 0x12, 0x1b, 0x98, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x16, 0xfb, 0xfc,
	0x3d, 0x01, 0x00, 0x00,
}

func (m *TxTokenPay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxTokenPay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxTokenPay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Token_Vout) > 0 {
		for iNdEx := len(m.Token_Vout) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Token_Vout[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTxTokenPay(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Token_VoutTotal != 0 {
		i = encodeVarintTxTokenPay(dAtA, i, uint64(m.Token_VoutTotal))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Token_Vin) > 0 {
		for iNdEx := len(m.Token_Vin) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Token_Vin[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTxTokenPay(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Token_VinTotal != 0 {
		i = encodeVarintTxTokenPay(dAtA, i, uint64(m.Token_VinTotal))
		i--
		dAtA[i] = 0x10
	}
	if m.TxBase != nil {
		{
			size, err := m.TxBase.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTxTokenPay(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTxTokenPay(dAtA []byte, offset int, v uint64) int {
	offset -= sovTxTokenPay(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TxTokenPay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxBase != nil {
		l = m.TxBase.Size()
		n += 1 + l + sovTxTokenPay(uint64(l))
	}
	if m.Token_VinTotal != 0 {
		n += 1 + sovTxTokenPay(uint64(m.Token_VinTotal))
	}
	if len(m.Token_Vin) > 0 {
		for _, e := range m.Token_Vin {
			l = e.Size()
			n += 1 + l + sovTxTokenPay(uint64(l))
		}
	}
	if m.Token_VoutTotal != 0 {
		n += 1 + sovTxTokenPay(uint64(m.Token_VoutTotal))
	}
	if len(m.Token_Vout) > 0 {
		for _, e := range m.Token_Vout {
			l = e.Size()
			n += 1 + l + sovTxTokenPay(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTxTokenPay(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTxTokenPay(x uint64) (n int) {
	return sovTxTokenPay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TxTokenPay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxTokenPay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxTokenPay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxTokenPay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBase", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxBase == nil {
				m.TxBase = &TxBase{}
			}
			if err := m.TxBase.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token_VinTotal", wireType)
			}
			m.Token_VinTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Token_VinTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token_Vin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token_Vin = append(m.Token_Vin, &Vin{})
			if err := m.Token_Vin[len(m.Token_Vin)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token_VoutTotal", wireType)
			}
			m.Token_VoutTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Token_VoutTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token_Vout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token_Vout = append(m.Token_Vout, &Vout{})
			if err := m.Token_Vout[len(m.Token_Vout)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxTokenPay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTxTokenPay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTxTokenPay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTxTokenPay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxTokenPay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTxTokenPay
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTxTokenPay
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTxTokenPay
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTxTokenPay        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTxTokenPay          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTxTokenPay = fmt.Errorf("proto: unexpected end of group")
)
